export const Modules = {
  
    'Music': {
        something: 'Music',
        img: "",
        topics: ['Musicians', 'spheron', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        videos: '',
        videosHeading: '',
        notes: '',
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
        userId: [],
        creatorLink: '',
        username: '',
        creators: ['Musicians', 'spheron', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 1,
    },
    'Deployment': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 2,
        moduleImage:"https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'Build': {
        creators: ['Koii', 'Arweave', 'Ardrive',],
        description: 'This is a sample description',
        id: 3,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'Storage': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 4,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'APIs': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 5,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'ArFS': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 6,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'Community Tokens': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 7,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
    'Identity': {
        creators: ['Koii', 'Arweave', 'Ardrive', 'ArFS', 'nader', 'arweave', 'sam'],
        description: 'This is a sample description',
        id: 8,
        moduleImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        title: '',
    },
}