export const Creators = {
    '1': {
        description: 'This is a sample Music creator',
        creatorName: 'Journey',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "1k8craCGpgs",
        videoImage: "https://img.youtube.com/vi/1k8craCGpgs/maxresdefault.jpg",
        videoTitle: "Dont stop Believin",
        videoHeading: "Journey - Dont stop Believin",
        userId: '1',
        createdVideosByID: ['VideoID'],
        authorLink: "https://twitter.com/JourneyOfficial",
        username: "@JourneyOfficial",
        author: "Journey",
        website: "https://twitter.com/JourneyOfficial",

    },
    '2': {
        creatorName: 'Eric_3.0',
        description: 'This is a sample description',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "PBJDM_ZY2WI",
        videoImage: "https://img.youtube.com/vi/PBJDM_ZY2WI/maxresdefault.jpg",
        videoTitle: "Koii Fundraiser",
        id: 2,
        createdVideosByID: ['VideoID'],
        videoHeading: "Deploying a React App with Koii, Arweave and Spheron",
        notes: "",
        userId: "2",
        authorLink: "https://twitter.com/KoiiEric",
        username: "@KoiiEric",
        author: "Koii-X",
        website: "https://docs.koii.network/build-dapps-with-koii/template-library/deploy",
    },
    '3': {
        creatorName: 'Spheron',
        description: 'This is a sample description',
        id: 3,
        editors: {
            preferred: "graphql",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "Ynfwggyl5rY",
        videoImage: "https://img.youtube.com/vi/Ynfwggyl5rY/maxresdefault.jpg",
        videoTitle: "Spheron",
        videoHeading: "Deploying a React App with Koii, Arweave and Spheron",
        notes: "",
        userId: "3",
        createdVideosByID: ['VideoID'],
        authorLink: "https://twitter.com/prashant_xyz",
        username: "@prashant_xyz",
        author: "Shperon",
        website: "https://spheron.network/",
    },
    '4': {
        creatorName: 'MC Lars',
        description: 'This is a sample description',
        id: 4,
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Ardrive-ArFS?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "y_wZE2G3Ygo",
        videoImage: "https://img.youtube.com/vi/y_wZE2G3Ygo/maxresdefault.jpg",
        videoHeading: "Learning to use GraphQL with Arweave and Graph Protocol",
        videoTitle: "Ardrive",
        notes: "",
        userId:"4",
        createdVideosByID: ['VideoID'],
        authorLink: "https://ardrive.io/",
        username: "@ardriveapp",
        author: "Ardrive",
        website: "https://ardrive.io/",
    },
    '5': {
        creatorName: 'Saeta',
        description: 'This is a sample description',
        id: 5,
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/nextExample?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "y_wZE2G3Ygo&t=4s",
        videoImage: "https://img.youtube.com/vi/y_wZE2G3Ygo/maxresdefault.jpg",
        videoHeading: "Deploying a Next.js App with ARKB",
        videoTitle: "Saeta",
        notes: "",
        userId: "5",
        authorLink: "https://twitter.com/saetaeth",
        username: "@saetaeth",
        author: "@saetaeth",
        website: "https://github.com/saeta-eth/arweave-nextjs-example",
    },
    '6': {
        creatorName: 'Nader',
        description: 'This is a sample description',
        id: 6,
        editors: {
            preferred: "arcodeArweave",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "https://us.glassapi.xyz/1647306621.NfBRvNpXJ38Mc_h42c9Zehmc8i34iVWiNu5Vu1_IC0Q.ac925d47-4a07-4c84-859b-9924f84708b9_uploaded_video_1_1_audio.mp4",
        videoImage: "https://img.youtube.com/vi/y_wZE2G3Ygo/maxresdefault.jpg",
        videoHeading: "Full stack web3 tutorial",
        notes: "",
        userId:"6",
        authorLink: "https://twitter.com/dabit3",
        username: "@dabit3",
        author: "Edge and Node",
        website: "https://edgeandnode.com/",
    },
    '7': {
        creatorName: 'Arweave',
        description: 'This is a sample description',
        id: 7,
        editors: {
            preferred: "graphql",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            koiiRepl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "https://arweave.net/9eWS7cfKeNAqPRTrSvMNR-4ub7JEwyOiI4IDXXkUMso",
        videoImage: "https://img.youtube.com/vi/y_wZE2G3Ygo/maxresdefault.jpg",
        videoHeading: "Introduction to Arweave",
        notes: "",
        userId: "7",
        authorLink: "https://twitter.com/onlyarweave",
        username: "@onlyarweave",
        author: "Arweave.org",
        website: "https://www.arweave.org/",
    },
    '8': {
        creatorName: 'Sam Williams',
        description: 'This is a sample description',
        id: 8,
        editors: {
            preferred: "arcode",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            koiiRepl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            graphql: "https://arweave.net/graphql"
        },
        videoSrc: "https://arweave.net/xlraoyFTfk9l4RvaCJ86IYe51xeVEA-gI7KC2hTwh6o",
        videoImage: "https://img.youtube.com/vi/y_wZE2G3Ygo/maxresdefault.jpg",
        videoHeading: "Arweave Build Program",
        notes: "",
        userId: "8",
        authorLink: "https://twitter.com/samecwilliams",
        username: "@samecwilliams",
        author: "Sam Williams",
        website: "https://arwiki.wiki/#/en/creating-a-dapp",
    }
}


