export const Authors = {
    '1': {
        author: "1",
        authorLink: "https://twitter.com/1UniverseMusic",
        authorName: "1",
        authorWebsite: "https://1universe.fm/",
        createdVideosByID: ['VideoID'],
        uid: '1',
        username: "@1UniverseMusic",
    },
    '2': {
        authorLink: "https://twitter.com/KoiiNetwork",
        author: "Koii-X",
        authorWebsite: "https://docs.koii.network/build-dapps-with-koii/template-library/deploy",
        createdVideosByID: ['VideoID'],
        uid: 2,
        username: "@KoiiEric",
    },
    '3': {
        authorLink: "https://twitter.com/spheronHQ",
        author: "Shperon",
        authorWebsite: "https://spheron.network/",
        createdVideosByID: ['VideoID'],
        uid: "3",
        username: "@SpheronHQ",
    },
    '4': {
        author: "Ardrive",
        authorLink: "https://twitter.com/ardriveapp",
        authorWebsite: "https://ardrive.io/",
        createdVideosByID: ['VideoID'],
        uid: 4,
        username: "@ardriveapp",
    },
    '5': {
        author: 'Saeta',
        authorLink: "https://twitter.com/saetaeth",
        authorWebsite: "https://github.com/saeta-eth/arweave-nextjs-example",
        createdVideosByID: ['VideoID'],
        uid: "5",
        username: "@saetaeth",
    },
    '6': {
        author: "Edge and Node",
        authorLink: "https://twitter.com/dabit3",
        authorWebsite: "https://edgeandnode.com/",
        createdVideosByID: ['6', '9'],
        uid: 6,
        username: "@edgeandnode",
    },
    '7': {
        author: 'Arweave',
        authorLink: "https://twitter.com/onlyarweave",
        authorWebsite: "https://www.onlyarweave.com/",
        createdVideosByID: ['VideoID'],
        uid: "7",
        username: "@onlyarweave",
    },
    '8': {
        author: 'Sam Williams',
        authorLink: "https://twitter.com/samecwilliams",
        authorWebsite: "https://arweave.build/",
        createdVideosByID: ['VideoID'],
        uid: 8,
        username: "@samecwilliams",
    }
}