export const Authors = {
    '1': {
        authorLink: "https://twitter.com/1UniverseMusic",
        authorName: "1",
        authorWebsite: "https://1universe.fm/",
        createdVideosByID: ['1'],
        createdContentByID: ['ContentID'],
        uid: 1,
        username: "@1UniverseMusic",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '2': {
        authorLink: "https://twitter.com/KoiiNetwork",
        author: "Koii-X",
        authorWebsite: "https://docs.koii.network/build-dapps-with-koii/template-library/deploy",
        createdVideosByID: ['2'],
        createdContentByID: ['ContentID'],
        uid: 2,
        username: "@KoiiNetwork",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '3': {
        authorLink: "https://twitter.com/spheronHQ",
        author: "Shperon",
        authorWebsite: "https://spheron.network/",
        createdVideosByID: ['3'],
        createdContentByID: ['ContentID'],
        uid: 3,
        username: "@SpheronHQ",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '4': {
        author: "Ardrive",
        authorLink: "https://twitter.com/ardriveapp",
        authorWebsite: "https://ardrive.io/",
        createdVideosByID: ['4', "10"],
        createdContentByID: ['ContentID'],
        uid: 4,
        username: "@ardriveapp",
        avatar: "	https://edgeandnode.com/images/logo-big.png",

    },
    '5': {
        author: 'Saeta',
        authorLink: "https://twitter.com/saetaeth",
        authorWebsite: "https://github.com/saeta-eth/arweave-nextjs-example",
        createdVideosByID: ['5'],
        createdContentByID: ['ContentID'],
        uid: 5,
        username: "@saetaeth",
        avatar: "	https://edgeandnode.com/images/logo-big.png",

    },
    '6': {
        author: "Edge and Node",
        authorLink: "https://twitter.com/dabit3",
        authorWebsite: "https://edgeandnode.com/",
        createdVideosByID: ['6', '9'],
        createdContentByID: ['ContentID'],
        uid: 6,
        username: "@edgeandnode",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '7': {
        author: 'Arweave',
        authorLink: "https://twitter.com/onlyarweave",
        authorWebsite: "https://www.onlyarweave.com/",
        createdVideosByID: ['7'],
        createdContentByID: ['ContentID'],
        uid: 7,
        username: "@onlyarweave",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '8': {
        author: 'Sam Williams',
        authorLink: "https://twitter.com/samecwilliams",
        authorWebsite: "https://arweave.build/",
        createdVideosByID: ['8'],
        createdContentByID: ['ContentID'],
        uid: 8,
        username: "@samecwilliams",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    },
    '9': {
        author: 'Redstone',
        authorLink: "https://twitter.com/redstone_defi",
        authorWebsite: "https://redstone.finance/",
        createdVideosByID: ['11'],
        createdContentByID: ['ContentID'],
        uid: 9,
        username: "@redstone_defi",
        avatar: "	https://edgeandnode.com/images/logo-big.png",
    }
}